server.port=8080


# Connexion MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate genere/met a jour les tables automatiquement
spring.jpa.hibernate.ddl-auto=update

# Affiche le SQL dans la console (utile pour debuguer)
spring.jpa.show-sql=true

# Dialect MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*
spring.web.cors.exposed-headers=Location
